### ISSUE TITLE
Detection docker image build - Dockerfile parse error

### ISSUE THREAD

**Issue by aielawady** [Moetaz-M-Mokhtar/ITIintake40_FaceRecognition#4]
Whenever I try to build the detection image I get this error message.

`ERROR: Dockerfile parse error line 1: FROM requires either one or three arguments`

**Comment by Moetaz-M-Mokhtar** [comment]
check the last commit in the gpu_fix branch let me know if it works for you ... after more tests i will merge the fix to the master branch soon hopefully
