### ISSUE TITLE
Face recognition dockerfile error

### ISSUE THREAD

**Issue by aielawady** [Moetaz-M-Mokhtar/ITIintake40_FaceRecognition#5]
It seems like the base image doesn't exist.
```
Building face_recognition
Step 1/10 : FROM tensorflow/tensorflow:1.15-gpu
ERROR: Service 'face_recognition' failed to build: manifest for tensorflow/tensorflow:1.15-gpu not found: manifest unknown: manifest unknown
```

**Comment by Moetaz-M-Mokhtar** [comment]
i am already aware of this problem and trying to solve it with some other dependency issues in the gpu_fix branch the last commit there fixed this problem but it isn't merged with master yet 
please let me know if that helped
